//! Cross-language parity: the Rust kernel must reproduce the committed
//! golden vectors generated by the independent SciPy reference
//! (`quant/src/slayer_quant/golden.py`). Drift between languages is a test
//! failure, not a code-review debate.

#![allow(clippy::unwrap_used)]

use serde::Deserialize;
use slayer_core::{Candle, OptionRight, TsMillis};
use slayer_quant::black_scholes::{self, BsInputs};
use slayer_quant::dist;
use slayer_quant::realized_vol;

/// Absolute tolerance for distribution functions (Hart/AS241 vs SciPy).
const DIST_TOL: f64 = 1e-12;
/// Absolute tolerance for BSM analytics (same closed form, different CDFs).
const BS_TOL: f64 = 1e-10;
/// Absolute tolerance for realized-vol estimators (pure arithmetic; only
/// summation order differs).
const RV_TOL: f64 = 1e-12;

fn golden(name: &str) -> String {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../schema/golden/");
    std::fs::read_to_string(format!("{path}{name}")).expect("golden file must exist")
}

#[derive(Deserialize)]
struct NormGolden {
    cdf: Vec<CdfCase>,
    ppf: Vec<PpfCase>,
}

#[derive(Deserialize)]
struct CdfCase {
    x: f64,
    value: f64,
}

#[derive(Deserialize)]
struct PpfCase {
    p: f64,
    value: f64,
}

#[test]
fn norm_dist_matches_scipy_goldens() {
    let g: NormGolden = serde_json::from_str(&golden("norm_dist.json")).unwrap();
    for c in g.cdf {
        assert!((dist::norm_cdf(c.x) - c.value).abs() < DIST_TOL, "cdf({})", c.x);
    }
    for c in g.ppf {
        assert!((dist::norm_cdf_inv(c.p) - c.value).abs() < DIST_TOL, "ppf({})", c.p);
    }
}

#[derive(Deserialize)]
struct BsCase {
    spot: f64,
    strike: f64,
    t_years: f64,
    vol: f64,
    rate: f64,
    div_yield: f64,
    right: String,
    price: f64,
    delta: f64,
    gamma: f64,
    theta: f64,
    vega: f64,
    vanna: f64,
    charm: f64,
}

#[test]
fn black_scholes_matches_scipy_goldens() {
    let cases: Vec<BsCase> = serde_json::from_str(&golden("black_scholes.json")).unwrap();
    assert!(!cases.is_empty());
    for c in cases {
        let inputs = BsInputs {
            spot: c.spot,
            strike: c.strike,
            t_years: c.t_years,
            vol: c.vol,
            rate: c.rate,
            div_yield: c.div_yield,
        };
        let right = match c.right.as_str() {
            "CALL" => OptionRight::Call,
            "PUT" => OptionRight::Put,
            other => panic!("unknown right {other}"),
        };
        let tag = format!("K={} vol={} t={} {}", c.strike, c.vol, c.t_years, c.right);
        let p = black_scholes::price(&inputs, right).unwrap();
        assert!((p - c.price).abs() < BS_TOL, "{tag} price {p} vs {}", c.price);
        let g = black_scholes::greeks(&inputs, right).unwrap();
        for (got, want, name) in [
            (g.delta, c.delta, "delta"),
            (g.gamma, c.gamma, "gamma"),
            (g.theta, c.theta, "theta"),
            (g.vega, c.vega, "vega"),
            (g.vanna, c.vanna, "vanna"),
            (g.charm, c.charm, "charm"),
        ] {
            assert!((got - want).abs() < BS_TOL, "{tag} {name} {got} vs {want}");
        }
    }
}

#[derive(Deserialize)]
struct RvGolden {
    periods_per_year: f64,
    candles: Vec<[f64; 4]>,
    estimates: RvEstimates,
}

#[derive(Deserialize)]
struct RvEstimates {
    close_to_close: f64,
    parkinson: f64,
    garman_klass: f64,
    rogers_satchell: f64,
    yang_zhang: f64,
}

#[test]
fn realized_vol_matches_scipy_goldens() {
    let g: RvGolden = serde_json::from_str(&golden("realized_vol.json")).unwrap();
    let candles: Vec<Candle> = g
        .candles
        .iter()
        .enumerate()
        .map(|(i, [o, h, l, c])| Candle {
            ts: TsMillis(i as u64),
            open: *o,
            high: *h,
            low: *l,
            close: *c,
            volume: 0.0,
        })
        .collect();
    let p = g.periods_per_year;
    let cases = [
        (realized_vol::close_to_close(&candles, p).unwrap(), g.estimates.close_to_close, "ctc"),
        (realized_vol::parkinson(&candles, p).unwrap(), g.estimates.parkinson, "parkinson"),
        (realized_vol::garman_klass(&candles, p).unwrap(), g.estimates.garman_klass, "gk"),
        (realized_vol::rogers_satchell(&candles, p).unwrap(), g.estimates.rogers_satchell, "rs"),
        (realized_vol::yang_zhang(&candles, p).unwrap(), g.estimates.yang_zhang, "yz"),
    ];
    for (got, want, name) in cases {
        assert!((got - want).abs() < RV_TOL, "{name}: {got} vs {want}");
    }
}
